# Generated by Django 2.0.7 on 2020-02-22 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='runsubmit',
            name='dataset',
            field=models.CharField(choices=[('cifar-20', 'cifar-20'), ('cifar-100', 'cifar-100')], default='default', help_text='数据集选择', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='runsubmit',
            name='gpu',
            field=models.CharField(choices=[('gtx1080ti', 'gtx1080ti'), ('Two', 'Two'), ('Three', 'Three')], default='gtx-1080ti', help_text='gpu使用', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='runsubmit',
            name='img',
            field=models.CharField(choices=[('One', 'One'), ('Two', 'Two'), ('Three', 'Three')], default='One', help_text='镜像信息', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='runsubmit',
            name='ind',
            field=models.CharField(choices=[('套餐一', '套餐一'), ('套餐二', '套餐二')], default='One', help_text='评测指标', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='runsubmit',
            name='modelname',
            field=models.CharField(default='default', max_length=20),
        ),
        migrations.AddField(
            model_name='runsubmit',
            name='retrycount',
            field=models.CharField(default='1', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='runsubmit',
            name='model',
            field=models.FileField(blank=True, upload_to='%Y%m%d/Models'),
        ),
    ]
