# Generated by Django 2.0.7 on 2020-02-14 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='runSubmit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('img', models.CharField(choices=[('One', 'One'), ('Two', 'Two'), ('Three', 'Three')], help_text='镜像信息', max_length=10)),
                ('gpu', models.CharField(choices=[('One', 'gtx1080ti'), ('Two', 'Two'), ('Three', 'Three')], help_text='gpu使用', max_length=10)),
                ('retrycount', models.PositiveIntegerField(default=0)),
                ('description', models.TextField()),
                ('dataset', models.CharField(choices=[('One', 'cifar-20'), ('Two', 'cifar-100')], help_text='数据集选择', max_length=10)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('ind', models.CharField(choices=[('One', '套餐一'), ('Two', '套餐二')], help_text='评测指标', max_length=10)),
                ('model', models.FileField(blank=True, upload_to='Models/%Y%m%d')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='tasksubmit',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
