# Generated by Django 2.1.5 on 2020-03-07 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0002_auto_20200222_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='runsubmit',
            name='model',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='tasksubmit',
            name='dataset',
            field=models.FileField(default='NO dataset', null=True, upload_to='%Y%m%d/DataSets/', verbose_name='任务数据集'),
        ),
        migrations.AlterField(
            model_name='tasksubmit',
            name='img',
            field=models.ImageField(default='static/img/not_login_user.jpg', upload_to='%Y%m%d/task'),
        ),
        migrations.AddField(
            model_name='taskparticipant',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.TaskSubmit'),
        ),
    ]
