# Generated by Django 2.1.5 on 2020-03-08 03:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0003_auto_20200307_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskparticipant',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='taskparticipant',
            name='task',
        ),
        migrations.AddField(
            model_name='tasksubmit',
            name='participant',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tasksubmit',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='TaskParticipant',
        ),
    ]
