# Generated by Django 2.2.3 on 2020-04-02 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0004_auto_20200308_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runsubmit',
            name='description',
        ),
        migrations.RemoveField(
            model_name='runsubmit',
            name='gpu',
        ),
        migrations.RemoveField(
            model_name='runsubmit',
            name='img',
        ),
        migrations.RemoveField(
            model_name='runsubmit',
            name='retrycount',
        ),
        migrations.RemoveField(
            model_name='runsubmit',
            name='title',
        ),
        migrations.RemoveField(
            model_name='tasksubmit',
            name='category',
        ),
        migrations.AddField(
            model_name='runsubmit',
            name='algorithm',
            field=models.CharField(choices=[('算法一', '算法一'), ('算法二', '算法二'), ('算法三', '算法三')], default='算法一', help_text='攻击算法', max_length=10),
        ),
        migrations.AddField(
            model_name='runsubmit',
            name='public',
            field=models.CharField(choices=[('公开', '公开'), ('私有', '私有')], default='私有', max_length=10),
        ),
        migrations.AddField(
            model_name='runsubmit',
            name='state',
            field=models.CharField(choices=[('评测中', '评测中'), ('暂停', '暂停'), ('完成', '完成')], default='评测中', max_length=10),
        ),
        migrations.AddField(
            model_name='tasksubmit',
            name='algorithm',
            field=models.CharField(choices=[('算法一', '算法一'), ('算法二', '算法二'), ('算法三', '算法三')], default='算法一', max_length=20),
        ),
        migrations.AddField(
            model_name='tasksubmit',
            name='endTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tasksubmit',
            name='ind',
            field=models.CharField(choices=[('类型一', '类型一'), ('类型二', '类型二')], default='类型一', help_text='评测指标', max_length=10),
        ),
        migrations.AddField(
            model_name='tasksubmit',
            name='modelType',
            field=models.CharField(default='default', max_length=20),
        ),
        migrations.AddField(
            model_name='tasksubmit',
            name='startTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tasksubmit',
            name='submit',
            field=models.ManyToManyField(to='management.runSubmit'),
        ),
        migrations.AddField(
            model_name='tasksubmit',
            name='tag',
            field=models.CharField(default='Img', max_length=20),
        ),
        migrations.AlterField(
            model_name='runsubmit',
            name='dataset',
            field=models.CharField(default='default', max_length=20),
        ),
        migrations.AlterField(
            model_name='runsubmit',
            name='ind',
            field=models.CharField(choices=[('类型一', '类型一'), ('类型二', '类型二')], default='类型一', help_text='评测指标', max_length=10),
        ),
        migrations.AlterField(
            model_name='tasksubmit',
            name='dataset',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='Task_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitNum', models.PositiveIntegerField(default=0)),
                ('best', models.PositiveIntegerField(default=0)),
                ('bestTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.TaskSubmit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Datasets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('specifications', models.CharField(max_length=10)),
                ('dataType', models.CharField(max_length=10)),
                ('public', models.CharField(choices=[('公开', '公开'), ('私有', '私有')], default='私有', max_length=3)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('datasets', models.FileField(upload_to='DataSets/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
