# Generated by Django 2.2.3 on 2020-04-02 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20200402_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksubmit',
            name='dataset',
            field=models.CharField(default='default', max_length=20),
        ),
    ]
