# Generated by Django 2.2.3 on 2020-04-03 14:13

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('management', '0009_auto_20200403_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasksubmit',
            name='tag',
        ),
        migrations.AddField(
            model_name='tasksubmit',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='tasksubmit',
            name='modelType',
            field=models.CharField(choices=[('类型一', '类型一'), ('类型二', '类型二')], default='类型一', max_length=20),
        ),
    ]
