# Generated by Django 2.2.3 on 2020-06-07 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_auto_20200607_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attack_method',
            old_name='attack_method',
            new_name='name',
        ),
    ]
