# Generated by Django 2.1.5 on 2020-01-18 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('privileges', '0003_user_sex'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Profile',
        ),
    ]
